### ISSUE TITLE
patch of a root array does not work

### ISSUE THREAD

**Issue by cheenu2** [flipkart-incubator/zjsonpatch#100]
## Expected Behavior
![Screenshot_2019-03-29_12-08-34](https://user-images.githubusercontent.com/5622708/55250275-d3a65a00-521b-11e9-9580-39562ad071bb.png)

## Actual Behavior
[REPLACE Operation] Missing field "0" at root
	at com.flipkart.zjsonpatch.JsonPatch.process(JsonPatch.java:112)
	at com.flipkart.zjsonpatch.JsonPatch.apply(JsonPatch.java:127)
	at com.flipkart.zjsonpatch.JsonPatch.apply(JsonPatch.java:132)

**Comment by cheenu2** [comment]
Sorry, my mistake .. had incorrect input .. closing.
