### ISSUE TITLE
Diff then patch fails on certain json

### ISSUE THREAD

**Issue by robseed** [flipkart-incubator/zjsonpatch#116]
## Expected Behavior
If JsonDiff.asJson succeeds then JsonPatch.apply should succeed

## Actual Behavior
JsonPatch.apply fails with `[MOVE Operation] Missing field`

## Steps to Reproduce the Problem

```
ObjectMapper mapper = new ObjectMapper();
JsonNode source = mapper.readTree("{\"16\":[{\"id\":\"one\",\"type\":\"page\",\"length\":1}],\"63\":[{\"id\":\"two\",\"length\":2}],\"76\":[{\"id\":\"three\",\"length\":3}]}");
JsonNode target = mapper.readTree("{\"16\":[{\"id\":\"four\",\"length\":4}],\"76\":[{\"id\":\"five\",\"type\":\"page\",\"length\":5}]}");
JsonNode diff = JsonDiff.asJson(source, target);
JsonPatch.apply(diff, source);

[MOVE Operation] Missing field "77" at root
	at com.flipkart.zjsonpatch.JsonPatch.process(JsonPatch.java:112)
	at com.flipkart.zjsonpatch.JsonPatch.apply(JsonPatch.java:127)
	at com.flipkart.zjsonpatch.JsonPatch.apply(JsonPatch.java:132)
```

## Specifications
The json looks contrived, but it is a real world example from comparing facebook posts.
Java 1.8, Jackson 2.9.9, zjsonpatch 0.4.9

**Comment by holograph** [comment]
Error reproduced, I'm looking into it. Especially with the error message it is indeed quite strange.

**Comment by holograph** [comment]
OK, the problem has to do with JSON Pointer semantics. When processing a list of diffs to introduce `move` ops, the assumption is the a numerical path segment is an array index (which means it has to be taken into account in adjusting the resulting paths). 

That is incorrect: JSON Pointer doesn't actually know whether a path segment refers to array or object. For example, the path `/0/abc` will correctly evaluate against both of these documents: `{"0": {"abc": true}}` and `[{"abc":true}]`. 

Solving this requires modifying `JsonDiff.introduceMoveOperation` and `JsonDiff.updatePath` to take the source document into account; I'm working on it, but it'll take a bit of time.

**Comment by lilylei013** [comment]
I meet similar issue, have a check on the source code,  here is my preliminary investigate, for reference only

Find Move and Copy operation have issues, maybe simiiar 
For copy, the possible problems spots related with JsonDiff.computeUnchangedValues,getUnchangedPart, use Map to save unchangedValues, but when there are cases exsit, value is same but path is not, example Boolean or String, it will get not corret result. 

For move , in  JsonDiff.introduceMoveOperation, will compare value for diffs , similar maybe case the node have similar value but in different path
